config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'home#index'
  get 'home/get_events'
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :companies, :contacts, :jobs
  
  resources :accounts do
    resources :countacts
  end

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                   :integer          not null, primary key
#  user_id              :integer
#  contact_id           :integer
#  title                :string(64)       not null
#  job_number           :string(12)
#  invoice_number       :string(12)
#  invoiced             :string(12)
#  stage                :string(23)       default("Inquiry")
#  starts_at            :time
#  ends_at              :time
#  confirmed_load_times :string(12)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  loads_in_at          :datetime
#  loads_out_at         :datetime
#  starts_on            :date
#  ends_on              :date
#  loads_in_on          :date
#  loads_out_on         :date
#

class Job < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
  
  validates :title, presence: true
  validates :contact_id, presence: true
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  
  def self.filtered
		all
	end
  
  def self.active
		where('starts_on >= ?', Date.today)
	end
	
	def self.to_be_invoiced
		where('ends_on < ?', Date.today).where('invoice_number = ?', "").where('invoiced = ?', "No") || where('ends_on < ?', Date.today).where('invoice_number = ?', "").where(:invoiced  => nil)
	end
	
# 	def self.closed
# 		where(arel_table[:ends_at].lt(Date.today)).where(invoiced: "Yes").where(arel_table[:invoice_number].not_eq(nil))
# 	end
	
	def self.closed
    where('ends_on < ?', Date.today).where('invoice_number <> ?', "").where(invoiced: "Yes")
  end
  
  def self.stage(stage)
    where('starts_on >= ?', Date.today).where(stage: stage)
  end
  
  
  # Testing
	
	def self.hired_since(date)
    where('start_date >= ?', date)
  end

	scope :by_period, -> starts_at, ends_at { where("starts_on = ? AND ends_on = ?", starts_at, ends_at) }
	
end

app/controllers/jobs_controller.rb
# == Schema Information
#
# Table name: jobs
#
#  id                   :integer          not null, primary key
#  user_id              :integer
#  contact_id           :integer
#  title                :string(64)       not null
#  job_number           :string(12)
#  invoice_number       :string(12)
#  invoiced             :string(12)
#  stage                :string(23)       default("Inquiry")
#  starts_at            :time
#  ends_at              :time
#  confirmed_load_times :string(12)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  loads_in_at          :datetime
#  loads_out_at         :datetime
#  starts_on            :date
#  ends_on              :date
#  loads_in_on          :date
#  loads_out_on         :date
#

class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  
  has_scope :filtered, :type => :boolean
  has_scope :active, :type => :boolean
  has_scope :closed, :type => :boolean
  has_scope :to_be_invoiced, :type => :boolean
  
  has_scope :stage

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:q]
      @q = Job.ransack(params[:q])
      @jobs = @q.result.paginate(:page => params[:page], :per_page => 6)
    else
      @q = Job.ransack(params[:q])
      @jobs = apply_scopes(Job).order("starts_on ASC").paginate(:page => params[:page], :per_page => 6)
		end
		
		@job_weeks = @jobs.order(:starts_on).group_by { |jobs| jobs.starts_on.beginning_of_week }
		@new_job = Job.new
		
		@count_jobs = Job.all.count
    @count_filtered = Job.filtered.count unless Job.filtered.count == 0
    @count_active = Job.active.count unless Job.active.count == 0
    @count_closed = Job.closed.count unless Job.closed.count == 0
    @count_to_be_invoiced = Job.to_be_invoiced.count unless Job.to_be_invoiced.count == 0
    
    # Counts for statuses
    @count_inquiry = Job.stage("Inquiry").count
    @count_tentative = Job.stage("Tentative").count
    @count_sold = Job.stage("Sold").count
    @count_cancelled = Job.stage("Cancelled").count
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :contact_id, :title, :job_number, :invoice_number, :invoiced, :stage, :starts_on, :starts_at, :ends_on, :ends_at, :loads_in_on, :loads_in_at, :loads_out_on, :loads_out_at, :confirmed_load_times)
    end
end

app/helpers/jobs_helper.rb
# == Schema Information
#
# Table name: jobs
#
#  id                   :integer          not null, primary key
#  user_id              :integer
#  contact_id           :integer
#  title                :string(64)       not null
#  job_number           :string(12)
#  invoice_number       :string(12)
#  invoiced             :string(12)
#  stage                :string(23)       default("Inquiry")
#  starts_at            :time
#  ends_at              :time
#  confirmed_load_times :string(12)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  loads_in_at          :datetime
#  loads_out_at         :datetime
#  starts_on            :date
#  ends_on              :date
#  loads_in_on          :date
#  loads_out_on         :date
#

module JobsHelper
end

app/views/jobs/_active_jobs_nav.html.erb
<ul class="nav nav-tabs nav-tabs-sm desktop">
  <li><%= link_to_in_li raw( "Active <span class='badge pull-right'>" + @count_active.to_s + "</span>"), controller: "jobs", active: "true" %></li>
  <% if Job.stage("Inquiry").count > 0 %>
    <li><%= link_to_in_li raw( "Inquiry <span class='badge pull-right'>" + @count_inquiry.to_s + "</span>"), controller: "jobs", stage: "Inquiry" %></li>
  <% end %>
  <% if Job.stage("Tentative").count > 0 %>
    <li><%= link_to_in_li raw( "Tentative <span class='badge pull-right'>" + @count_tentative.to_s + "</span>"), controller: "jobs", stage: "Tentative" %></li>
  <% end %>
  <% if Job.stage("Sold").count > 0 %>
    <li><%= link_to_in_li raw( "Sold <span class='badge pull-right'>" + @count_sold.to_s + "</span>"), controller: "jobs", stage: "Sold" %></li>
  <% end %>
  <% if Job.stage("Cancelled").count > 0 %>
    <li><%= link_to_in_li raw( "Cancelled <span class='badge pull-right'>" + @count_cancelled.to_s + "</span>"), controller: "jobs", stage: "Cancelled" %></li>
  <% end %>
</ul>
<ul class="nav nav-pills nav-stacked mobile">
  <li><%= link_to_in_li raw( "Active <span class='badge pull-right'>" + @count_active.to_s + "</span>"), controller: "jobs", active: "true" %></li>
  <% if Job.stage("Inquiry").count > 0 %>
    <li><%= link_to_in_li raw( "Inquiry <span class='badge pull-right'>" + @count_inquiry.to_s + "</span>"), controller: "jobs", stage: "Inquiry" %></li>
  <% end %>
  <% if Job.stage("Tentative").count > 0 %>
    <li><%= link_to_in_li raw( "Tentative <span class='badge pull-right'>" + @count_tentative.to_s + "</span>"), controller: "jobs", stage: "Tentative" %></li>
  <% end %>
  <% if Job.stage("Sold").count > 0 %>
    <li><%= link_to_in_li raw( "Sold <span class='badge pull-right'>" + @count_sold.to_s + "</span>"), controller: "jobs", stage: "Sold" %></li>
  <% end %>
  <% if Job.stage("Cancelled").count > 0 %>
    <li><%= link_to_in_li raw( "Cancelled <span class='badge pull-right'>" + @count_cancelled.to_s + "</span>"), controller: "jobs", stage: "Cancelled" %></li>
  <% end %>
</ul>

app/views/jobs/_form.html.erb
<div class="panel panel-default">
  <%= simple_form_for(@job) do |f| %>
    <div class="panel-body">
      <%= f.error_notification %>
      <div class="row">
        <div class="col-sm-6">
            <div class="row">
              <div class="col-sm-8"><%= f.input :title, label: 'Job Title', placeholder: 'New Job', autofocus: true, :input_html => {"data-bind" => "textInput: jobName" } %></div>
              <div class="col-sm-4"><%= f.input :stage, as: :select, collection: [ "Inquiry", "Tentative", "Sold", "Cancelled"], include_blank: false %></div>
            </div>
            <hr>
            <div class="row">
              <div class="col-xs-5"><%= f.input :job_number %></div>
              <div class="col-xs-5"><%= f.input :invoice_number %></div>
              <div class="col-xs-2"><%= f.input :invoiced, as: :select, collection: [ "No", "Yes"], include_blank: false %></div>
            </div>
            <hr>
            <%= f.association :contact, label_method: :full_name_and_account_association, value_method: :id, input_html: { id: 'dropdown' } %>
        </div>
        <div class="col-sm-6">
          <div class="row">
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.label :starts_on, '* Start Date', class: 'control-label'  %>
                <%= f.text_field :starts_on, :required => true, :value => @job.starts_on.try(:strftime, "%a, %b %d, %Y"), class: 'form-control starts_on_date' %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :starts_at, '* Start Time', class: 'control-label'  %>
                <%= f.text_field :starts_at, :value => @job.starts_at.try(:strftime, "%I:%M %P"), class: 'form-control starts_at_time' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.label :ends_on, '* End Date', class: 'control-label'  %>
                <%= f.text_field :ends_on, :required => true, :value => @job.ends_on.try(:strftime, "%a, %b %d, %Y"), class: 'form-control ends_on_date' %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :ends_at, '* End Time', class: 'control-label'  %>
                <%= f.text_field :ends_at, :value => @job.ends_at.try(:strftime, "%I:%M %P"), class: 'form-control ends_at_time' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.label :loads_in_on, 'Load In Date', class: 'control-label'  %>
                <%= f.text_field :loads_in_on, :value => @job.loads_in_on.try(:strftime, "%a, %b %d, %Y"), class: 'form-control loads_in_on_date' %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :loads_in_at, 'Load In Time', class: 'control-label'  %>
                <%= f.text_field :loads_in_at, class: 'form-control loads_in_at_time' %>
              </div>
            </div>
          <div class="row">
          </div>
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.label :loads_out_on, 'Load Out Date', class: 'control-label'  %>
                <%= f.text_field :loads_out_on, :value => @job.loads_out_on.try(:strftime, "%a, %b %d, %Y"), class: 'form-control loads_out_on_date' %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.label :loads_out_at, 'Load Out Time', class: 'control-label'  %>
                <%= f.text_field :loads_out_at, class: 'form-control loads_out_at_time' %>
              </div>
            </div>
          </div>
          <%= f.input :confirmed_load_times, as: :select, collection: [ "No", "Yes"], include_blank: false %>
        </div>
      </div>
    </div>
  <div class="panel-footer">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
    <% end %>
    <script>
      $(function() {
        $( "#dropdown" ).select2({
            theme: "bootstrap",
            allowClear: true,
            placeholder: 'Select a contact'
        });
      });
      $(function() {
          $('.starts_on_date, .ends_on_date, .loads_in_on_date, .loads_out_on_date').pickadate({
            labelMonthNext: 'Go to the next month',
            labelMonthPrev: 'Go to the previous month',
            labelMonthSelect: 'Pick a month from the dropdown',
            labelYearSelect: 'Pick a year from the dropdown',
            selectMonths: true,
            selectYears: true,
            format: 'ddd, mmm dd, yyyy',
            // formatSubmit: 'ddd, dd mmm yyyy',
            hiddenName: true
          });
          $('.starts_at_time, .ends_at_time, .loads_in_at_time, .loads_out_at_time').pickatime({
            format: 'h:i A',
            // formatSubmit: 'HH:i',
            interval: 15,
            hiddenName: true
          });
      });
    </script>
    <script>
      $(function() {
          var viewModel = {
              jobName : ko.observable("<%= @job.title unless @job.title.nil? %>")
          };
          viewModel.fullName = ko.dependentObservable(function () {
              return viewModel.jobName();
          });
      
          ko.applyBindings(viewModel);
      });
    </script>
</div>

app/views/jobs/_quick_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New <%= controller_name.singularize.titleize %></h3>
  </div>
  <%= simple_form_for(@new_job) do |f| %>
    <div class="panel-body">
        <%= f.error_notification %>
        <div class="row">
            <div class="col-sm-6">
                <%= f.input :title %>
            </div>
            <div class="col-sm-6">
                <%= f.association :contact, label_method: :first_name, value_method: :id, input_html: { id: 'dropdown' } %>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <%= f.label :starts_on, '* Start Date', class: 'control-label'  %>
                    <%= f.text_field :starts_on, :required => true, class: 'form-control starts_on_date' %>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <%= f.label :ends_on, '* End Date', class: 'control-label'  %>
                    <%= f.text_field :ends_on, :required => true, class: 'form-control ends_on_date' %>
                </div>
            </div>
        </div>
        <script>
          $(function() {
            $( "#dropdown" ).select2({
                theme: "bootstrap",
                allowClear: true,
                placeholder: 'Select a contact',
                width: '100%'
            });
          });
          $(function() {
              $('.starts_on_date, .ends_on_date').pickadate({
                labelMonthNext: 'Go to the next month',
                labelMonthPrev: 'Go to the previous month',
                labelMonthSelect: 'Pick a month from the dropdown',
                labelYearSelect: 'Pick a year from the dropdown',
                selectMonths: true,
                selectYears: true,
                format: 'ddd, mmm dd, yyyy',
                // formatSubmit: 'ddd, dd mmm yyyy',
                hiddenName: true
              });
          });
        </script>
    </div>
    <div class="panel-footer">
        <div class="form-group">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
    </div>
  <% end %>
</div>

app/views/jobs/_search_jobs.html.erb
<div class="panel panel-default">
  <%= search_form_for @q, class: 'search-inlines' do |f| %>
    <div class="panel-body">
      <div class="form-group">
        <%= f.search_field :title_cont, class: 'form-control', autofocus: true, placeholder: 'Job Name' %>
      </div>
      <div class="form-group">
        <a id="searchDatesButton" class="btn btn-default btn-block" type="button" data-toggle="collapse" data-target="#searchDates" aria-expanded="false" aria-controls="searchDates">
          Dates <i class="fa fa-plus"></i>
          <i class="fa fa-minus"></i>
        </a>
      </div>
      <div class="collapse" id="searchDates">
        <div class="form-group">
          <%= f.search_field :starts_on_gteq, class: 'form-control', placeholder: 'Start Date' %>
        </div>
        <div class="form-group">
          <%= f.search_field :ends_on_lteq, class: 'form-control', placeholder: 'End Date' %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
  	  <%= f.submit 'Search', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>

<script>
  $(function() {
      $('#q_starts_on_gteq, #q_ends_on_lteq').pickadate({
        labelMonthNext: 'Go to the next month',
        labelMonthPrev: 'Go to the previous month',
        labelMonthSelect: 'Pick a month from the dropdown',
        labelYearSelect: 'Pick a year from the dropdown',
        selectMonths: true,
        selectYears: true,
        format: 'Start: mmm dd, yyyy',
        // formatSubmit: 'ddd, dd mmm yyyy',
        hiddenName: true
      });
  });
</script>

app/views/jobs/_sidebar.html.erb
<h3 class='text-muted'>Filter</h3>
<ul class="nav nav-pills nav-stacked">
  <%= link_to_in_li raw( "Active Jobs <span class='badge pull-right'>" + @count_active.to_s + "</span>"), controller: "jobs", active: "true" %>
  <%= link_to_in_li raw( "Closed Jobs <span class='badge pull-right'>" + @count_closed.to_s + "</span>"), controller: "jobs", closed: "true" %>
  <%= link_to_in_li raw( "All Jobs <span class='badge pull-right'>" + @count_filtered.to_s + "</span>"), controller: "jobs", filtered: "true" %>
  <%= link_to_in_li raw( "To Be Invoiced <span class='badge pull-right'>" + @count_to_be_invoiced.to_s + "</span>"), controller: "jobs", to_be_invoiced: "true" %>
</ul>

app/views/jobs/edit.html.erb
<h3><span data-bind="text: jobName"></h3>

<%= render 'form' %>

<%= link_to 'Cancel', @job %>

app/views/jobs/index.html.erb
<div class="row">
  <div class="col-sm-9">
    <%= render 'layouts/entity_header' %>
    <%= render 'jobs/active_jobs_nav' %>
      <% @job_weeks.each do |week, jobs| %>
        <% end_of_week = week + 6.days %>
        <div class="panel panel-default jobs-index">
            <div class="panel-heading">
              <h4 class="panel-title"><%= week.strftime("%b %-d, %Y") %><small> - <%= end_of_week.strftime("%b %-d, %Y") %></small></h4>
            </div>
            <ul class="list-group">
              <% jobs.each do |job| %>
                <li class="list-group-item">
                  <%= link_to 'Edit', edit_job_path(job), class: 'pull-right' %>
                  <%= content_tag(:small, job.starts_on.strftime("%a, %d"), class: 'inline job-date-short') %> <span class="label label-<%= job.stage.downcase %>"><%= job.stage %></span> <%= link_to job.title, job, class: 'tooltips', title: "Job: #{job.job_number} / Invoice: #{job.invoice_number}", data: { toggle: 'tooltip', placement: 'top' } %><span class="text-muted"><% if !job.contact.first_name.blank? %> - <%= job.contact.first_name %><% end %><% if !job.contact.account.nil? %>, <%= job.contact.account.name %><% end %></span>
                </li>
              <% end %>
            </ul>
          <script>
            $(function () {
              $('[data-toggle="tooltip"]').tooltip()
            })
          </script>
        </div>
      <% end %>
    <div class="text-center">
      <%= will_paginate @job, renderer: BootstrapPagination::Rails %>
      <%= content_tag(:p, total_count(@jobs), class: 'text-center') %>
    </div>
  </div>
  <div class="col-sm-3">
    <%= render 'layouts/entity_sidebar' %>
    <%= render 'jobs/search_jobs' %>
    <%= render 'jobs/sidebar' %>
  </div>
</div>

app/views/jobs/new.html.erb
<h3><span data-bind="text: fullName"></h3>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<h1><%= @job.title %> <small><%= @job.stage %></small><%= link_to 'Edit', edit_job_path(@job), class: 'btn btn-default pull-right' %></h1>

<div class="row">
  <div class="col-sm-4">
    <ul class="list-group">
      <li class="list-group-item  list-group-item-<%= @job.stage.downcase %>"><span class="dt">Stage</span><%= @job.stage %></li>
      <li class="list-group-item"><span class="dt">Job Number</span><%= @job.job_number %></li>
      <li class="list-group-item"><span class="dt">Invoice Number</span><%= @job.invoice_number %></li>
      <li class="list-group-item"><span class="dt">Invoiced</span><%= @job.invoiced %></li>
      <li class="list-group-item"><span class="dt">Start Date</span><%= @job.starts_on.try(:strftime, "%a, %b %-d, %Y") %> 
      <%= @job.starts_at.try(:strftime, "@ %-l:%M %P") %></li>
      <li class="list-group-item"><span class="dt">End Date</span><%= @job.ends_on.try(:strftime, "%a, %b %-d, %Y") %> 
      <%= @job.ends_at.try(:strftime, "@ %-l:%M %P") %></li>
      <li class="list-group-item"><span class="dt">Loads In On</span><%= @job.loads_in_on.try(:strftime, "%a, %b %-d, %Y") %> 
      <%= @job.loads_in_at.try(:strftime, "@ %-l:%M %P") %></li>
      <li class="list-group-item"><span class="dt">Loads Out On</span><%= @job.loads_out_on.try(:strftime, "%a, %b %-d, %Y") %> 
      <%= @job.loads_out_at.try(:strftime, "@ %-l:%M %P") %></li>
      <li class="list-group-item"><span class="dt">Load I/O Times</span><% if @job.confirmed_load_times == "No" %>NOT confirmed<% elsif @job.confirmed_load_times == "Yes" %>Confirmed<% end %></li>
      <li class="list-group-item"><span class="dt">User</span><%= @job.user.first_name %></li>
      <li class="list-group-item"><span class="dt">Account</span><%= link_to @job.contact.account.name, @job.contact.account %></li>
      <li class="list-group-item"><span class="dt">Contact</span><%= link_to "#{@job.contact.first_name} #{@job.contact.last_name}", @job.contact %></li>
    </ul>
    
    <%= link_to 'Destroy', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
  </div>
</div>