config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'home#index'
  get 'home/get_events'
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :companies, :contacts, :jobs
  
  resources :accounts do
    resources :countacts
  end

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  first_name :string(64)
#  last_name  :string(64)
#  title      :string(64)
#  department :string(64)
#  source     :string(32)
#  email      :string(64)
#  alt_email  :string(64)
#  phone      :string(32)
#  mobile     :string(32)
#  fax        :string(32)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :integer
#

class Contact < ActiveRecord::Base
  
  default_scope { order("last_name ASC") }
  
  belongs_to :user
  belongs_to :account
  has_many :jobs
  
  accepts_nested_attributes_for :account
  
  validates :first_name, presence: true
  
  validates :phone, presence: true, :unless => :email?
  validates :email, presence: true, :unless => :phone?
  
  def full_name
    "#{@contact.first_name} #{@contact.last_name}"
  end
  
  def full_name_association
    "#{first_name} #{last_name}"
  end
  
  def full_name_and_account_association
    if !account_id.nil?
      account = Account.find(account_id)
      "#{first_name} #{last_name}, #{account.name}"
    else
      "#{first_name} #{last_name}"
    end
  end
    
end

app/controllers/contacts_controller.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  first_name :string(64)
#  last_name  :string(64)
#  title      :string(64)
#  department :string(64)
#  source     :string(32)
#  email      :string(64)
#  alt_email  :string(64)
#  phone      :string(32)
#  mobile     :string(32)
#  fax        :string(32)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :integer
#

class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    # @contacts = policy_scope(Contact)
    # @q = policy_scope(Contact).includes(:account).ransack(params[:q])
    @q = Contact.includes(:account).ransack(params[:q])
    @contacts = @q.result.paginate(:page => params[:page], :per_page => 10)
    if @contacts.count > 0 && @contacts.empty?
      redirect_to new_contact_path, notice: "no results for #{@q.first_name_or_last_name_or_account_name_cont}"
    elsif @contacts.count == 0
      redirect_to new_contact_path, notice: "There are no contacts yet, go ahead and create one."
    end
    @new_contact = Contact.new
    
    @recent = Contact.order(created_at: :desc).limit(5)
    # authorize Contact
    # raise Pundit::NotAuthorized unless current_user.role? :staff
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @job_years = @contact.jobs.order("starts_on DESC").group_by { |jobs| jobs.starts_on.beginning_of_year }
    # authorize @contact
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    # authorize @contact
  end

  # GET /contacts/1/edit
  def edit
    # authorize @contact
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    
    @contact.user_id = current_user.id
    
    # authorize @contact

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    authorize @contact
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    authorize @contact
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:user_id, :assigned_to, :first_name, :last_name, :title, :department, :source, :email, :alt_email, :phone, :mobile, :fax, :account_id)
    end
end

app/helpers/contacts_helper.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  first_name :string(64)
#  last_name  :string(64)
#  title      :string(64)
#  department :string(64)
#  source     :string(32)
#  email      :string(64)
#  alt_email  :string(64)
#  phone      :string(32)
#  mobile     :string(32)
#  fax        :string(32)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :integer
#

module ContactsHelper
end

app/views/contacts/_contact.html.erb
<% @account.contacts.each do |contact| %>
<li class="list-group-item"><span class="text-muted"><%= icon('glyphicon', 'user') %></span> <%= link_to "#{contact.first_name} #{contact.last_name}", contact %> <span class="pull-right text-muted"><%= contact.try(:title) %></span></li>
<% end %>

app/views/contacts/_form.html.erb
<script>
  $(function() {
    var viewModel = {
            firstName : ko.observable("<%= @contact.first_name unless @contact.first_name.nil? %>"),
            lastName : ko.observable("<%= @contact.last_name unless @contact.last_name.nil? %>")
        };
        viewModel.fullName = ko.dependentObservable(function () {
            return viewModel.firstName() + " " + viewModel.lastName();
        });

        ko.applyBindings(viewModel);
  });
</script>

<%= simple_form_for(@contact, html: { class: 'form-inline' }) do |f| %>
<div class="panel panel-default">
    <%= f.error_notification %>
    <ul class="list-group list-group-form">
        <li class="list-group-item">
        <div class="row">
          <div class="col-sm-3 label-col"><%= f.label :account %></div>
          <div class="col-sm-6">
            <%= f.association :account, input_html: { id: 'dropdown' }, label: false %>
          </div>
          <div class="col-sm-3">
              <%= link_to 'Add Account', new_account_path, class: 'btn btn-default btn-xs' %>
          </div>
        </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :first_name %></div>
            <div class="col-sm-9"><%= f.input :first_name, :input_html => {"data-bind" => "textInput: firstName" }, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :last_name %></div>
            <div class="col-sm-9"><%= f.input :last_name, :input_html => {"data-bind" => "textInput: lastName" }, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :title %></div>
            <div class="col-sm-9"><%= f.input :title, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :email %></div>
            <div class="col-sm-9"><%= f.input :email, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :alt_email %></div>
            <div class="col-sm-9"><%= f.input :alt_email, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :phone %></div>
            <div class="col-sm-9"><%= f.input :phone, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :mobile %></div>
            <div class="col-sm-9"><%= f.input :mobile, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :fax %></div>
            <div class="col-sm-9"><%= f.input :fax, label: false %></div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3 label-col"><%= f.label :source %></div>
            <div class="col-sm-9"><%= f.input :source, label: false %></div>
          </div>
        </li>
    </ul>
</div>
  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-primary' %> <%= link_to 'Cancel', @contact, class: 'btn btn-default' %>
  </div>
<% end %>
<br>
<script>
  $(function() {
    $( "#dropdown" ).select2({
        // theme: "bootstrap",
        allowClear: true,
        placeholder: 'Select an account if possible',
        width: "100%"
    });
  });
</script>

app/views/contacts/_form_contact.html.erb
<%= simple_form_for(@contact) do |f| %>
    <div class="form-group">
        <%= f.text_field :account_id, label: false, :value => @account.id, :hidden => true %>
        <%= f.input :first_name, label: false, placeholder: 'First Name' %>
        <%= f.input :last_name, label: false, placeholder: 'Last Name' %>
    </div>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></div>
            <%= f.input :email, label: false, placeholder: 'mail@example.com' %>
          </div>
    </div>
    <%= f.submit 'Save Contact', :class => 'btn btn-primary' %>
<% end %>

app/views/contacts/_jobs.html.erb
<% @job_years.each do |year, jobs| %>
    <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title"><%= year.strftime("%Y") %></h4>
        </div>
        <ul class="list-group">
            <% jobs.each do |job| %>
                <li class="list-group-item">
                    <%= link_to 'Edit', edit_job_path(job), class: 'pull-right' %>
                    <%= content_tag(:small, job.starts_on.strftime("%a, %b %-d"), class: 'inline job-date-long') %> <span class="label label-<%= job.stage.downcase %>"><%= job.stage %></span> <%= link_to job.title, job, class: 'tooltips', title: "Job: #{job.job_number} / Invoice: #{job.invoice_number}", data: { toggle: 'tooltip', placement: 'top' } %><span class="text-muted"><% if !job.contact.first_name.blank? %> - <%= job.contact.first_name %><% end %><% if !job.contact.account.nil? %>, <%= job.contact.account.name %><% end %></span>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/contacts/_quick_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New <%= controller_name.singularize.titleize %></h3>
  </div>
  <%= simple_form_for(@new_contact) do |f| %>
    <div class="panel-body">
        <%= f.error_notification %>
      
        <div class="row">
          <div class="col-sm-6"><%= f.input :first_name %></div>
          <div class="col-sm-6"><%= f.input :last_name %></div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
                <%= f.input :title, label: false, placeholder: 'Title' %>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></div>
                <%= f.input :email, label: false, placeholder: 'mail@example.com', error: 'An email or phone number is required' %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></div>
                <%= f.input :phone, label: false, placeholder: 'Phone Number', error: 'An email or phone number is required' %>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-phone" aria-hidden="true"></span></div>
                <%= f.input :mobile, label: false, placeholder: 'Mobile Number' %>
              </div>
            </div>
          </div>
        </div>
      
    </div>
    <div class="panel-footer">
        <div class="form-group">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
    </div>
  <% end %>
</div>

app/views/contacts/_search.html.erb
<%= search_form_for @q, class: 'search-inline' do |f| %>
  <div class="form-group">
    <%= f.search_field :first_name_or_last_name_or_account_name_cont, class: 'form-control', autofocus: true, placeholder: 'Search' %>
  </div>
	<%= f.submit 'Go', class: 'btn btn-primary' %>
<% end %>

app/views/contacts/edit.html.erb
<h3><span data-bind="text: fullName"></h3>
<div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>  
    </div>
</div>

<%= link_to 'Destroy', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-sm-9">
    <%= render 'layouts/entity_header' %>
    <ul class="list-group">
      <% @contacts.each do |contact| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-6">
              <span class="text-muted"><%= icon('glyphicon', 'user') %></span> <%= link_to "#{contact.first_name} #{contact.last_name }", contact %> <span class="text-muted"><% if !contact.title.blank? %> - <%= contact.title %><% end %> <% if !contact.account.nil? %>at <%= link_to contact.account.name, contact.account %><% end %></span>
            </div>
            <div class="col-sm-3">
              <small><%= contact.jobs.count %> <span class="stat-label">Jobs</span></small>
            </div>
            <div class="col-sm-3"><%= link_to 'Edit', edit_contact_path(contact), class: 'pull-right' %></div>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="text-center">
      <%= will_paginate @contact, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
  <div class="col-sm-3">
    <%= render 'layouts/entity_sidebar' %>
  </div>
</div>

app/views/contacts/new.html.erb
<h3><span data-bind="text: fullName"></h3>
<div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>  
    </div>
</div>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h1><%= "#{@contact.first_name} #{@contact.last_name}" %> <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-default' %></h1>

<div class="row">
  <div class="col-sm-5">
    <div class="panel panel-default">
      <ul class="list-group">
        <li class="list-group-item"><span class="dt">Title</span><%= @contact.title %></li>
        <li class="list-group-item"><span class="dt">Account</span>
        <% if !@contact.account.nil? %>
          <%= link_to @contact.account.name, @contact.account %>
        <% else %>
          <%= link_to 'Add Account', edit_contact_path(@contact) %>
        <% end %>
        </li>
        <%# @contact.assigned_to %>
        <li class="list-group-item"><span class="dt">Department</span><%= @contact.department %></li>
        <li class="list-group-item"><span class="dt">Source</span><%= @contact.source %></li>
        <li class="list-group-item"><span class="dt">Email</span><%= link_to @contact.email, "mailto:#{@contact.email}" %></li>
        <li class="list-group-item"><span class="dt">Alternate Email</span><%= link_to @contact.alt_email, "mailto:#{@contact.alt_email}" %></li>
        <li class="list-group-item"><span class="dt">Phone</span><%= link_to phone(@contact.phone), "tel:#{phone(@contact.phone)}" %></li>
        <li class="list-group-item"><span class="dt">Mobile</span><%= link_to phone(@contact.mobile), "tel:#{phone(@contact.mobile)}" %></li>
        <li class="list-group-item"><span class="dt">Fax</span><%= phone(@contact.fax) %></li>
      </ul>
      <div class="panel-footer">
        <small>Added on <%= @contact.created_at.strftime("%-m/%-d/%Y at %-l:%M %P") %> by <%= "#{@contact.user.first_name} #{@contact.user.last_name}" %></small>
      </div>
    </div>
    <%= link_to 'Destroy', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
  </div>
  <div class="col-sm-7">
    <h3>Jobs</h3>
    <div class="jobs">
      <%= render 'jobs' %>
    </div>
  </div>
</div>