config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'home#index'
  get 'home/get_events'
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :companies, :contacts, :jobs
  
  resources :accounts do
    resources :countacts
  end

end

app/views/layouts/_entity_header.html.erb
<div class="row">
  <div class="col-sm-12 col-lg-3">
    <h1><%= controller_name.titleize %> <small><a id="quickAddButton" type="button" data-toggle="collapse" data-target="#quickAdd" aria-expanded="false" aria-controls="quickAdd">
        <i class="fa fa-plus"></i>
        <i class="fa fa-minus"></i>
      </a></small></h1>
  </div>
  <div class="col-sm-12 col-lg-9">
    <span class="pull-right"><%= render "search" %></span>
  </div>
</div>

<div class="collapse" id="quickAdd">
  <%= render "#{controller_name}/quick_form" %>
</div>

app/views/layouts/_entity_sidebar.html.erb
<% "new_#{controller_name.singularize}_path" %>
<h3 class='text-muted'>Sidebar</h3>
<%= link_to "New #{controller_name.singularize.titleize}", new_entity_path, class: 'btn btn-default btn-block' %>
<a href="javascript:if(window.print)window.print()" class="btn btn-default btn-block"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print</a>
<br>
<% if defined? @recent %>
  <div class="list-group">
    <li class="list-group-item title"><strong>Recent <%= controller_name.titleize %></strong></li>
    <% @recent.each do |item| %>
      <% if controller_name == "contacts" %>
        <%= link_to "#{item.first_name} #{item.last_name}", item, class: 'list-group-item' %>
      <% elsif controller_name == "accounts" %>
        <%= link_to item.name, item, class: 'list-group-item' %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="btn btn-link navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <% if user_signed_in? %>
      <%= link_to raw("<i class='glyphicon glyphicon-tasks'></i> #{current_user.company.name}"), root_path, class: 'navbar-brand' %>
      <% else %>
      <%= link_to raw("<i class='glyphicon glyphicon-tasks'></i> Rental CRM"), root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? && current_user.user? %>
        <li><%= link_to raw('<i class="fa fa-users"></i> Contacts'), contacts_path %></li>
        <li><%= link_to raw('<i class="fa fa-building"></i> Accounts'), accounts_path %></li>
        <li><%= link_to raw('<i class="fa fa-truck"></i> Jobs'), controller: "jobs", active: "true" %></li>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to raw('<i class="fa fa-users"></i> Users'), users_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.user? %>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to raw('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log Out'), destroy_user_session_path, method: 'delete' %></li>
        <% elsif user_signed_in? && current_user.admin? %>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to raw('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log Out'), destroy_user_session_path, method: 'delete' %></li>
        <% end %>
        <% if !user_signed_in? %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to raw('<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log In'), new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rental CRM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <%# render 'favicon' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body class="<%= body_class %>">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%# content_tag(:div, msg, class: "alert alert-#{name}") %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
  <%# render 'layouts/footer' %>
</body>
</html>